<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BridgePackageSource\**\*.cs" />
    <Compile Remove="artifacts\**\*.cs" />
    <Content Remove="BridgePackageSource\**\*" />
    <None Remove="BridgePackageSource\**\*" />
    <Content Remove="artifacts\**\*" />
    <None Remove="artifacts\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tessdata\*.traineddata" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Data\SeedData\icd102019enMeta.zip" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Data\SeedData\icd10tm2019-update-202405.xlsx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

</Project>
